### PR TITLE
Fix incorrect provider error

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request removes the dummy `region` arguments inside the `provider` blocks.  I also pulled in upstream changes.  The key commit is 5da4a4c.

## 💭 Motivation and Context

The dummy `region` arguments inside the `provider` blocks were causing the code in `examples/basic_usage` to fail to apply.  This is because providing the `region` argument actually results in an explicit provider (using the default profile) being created.  As stated in the penultimate paragraph in [this section](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly), "a proxy provider block is one that is either completely empty or that contains only the `alias` argument."

## 🧪 Testing

The code inside of `examples/basic_usage` successfully applies again.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
@dav3r and @mcdonnnj, it appears that what makes `terraform validate` happy leads to incorrect behavior.  What should we do with the `terraform validate` `pre-commit` hook?  It should be OK to run it on any directory inside of `examples`, and that should check the module code indirectly, but it cannot be run on the actual module code.

In short, module `provider` blocks can contain no arguments other than `alias`.

**Review by hillaryj — APPROVED** [review]
🎉

**Comment by hillaryj** [comment]
It's now failing to build/lint on the `terraform validate` step because the region is missing.

**Comment by jsf9k** [comment]
> It's now failing to build/lint on the `terraform validate` step because the region is missing.

Yep.  I was waiting on cisagov/skeleton-generic#44 to trickle down.  I got impatient, though, so I went ahead and `git cherry-pick`ed the relevant commits from there and applied them here.

**Review by dav3r — APPROVED** [review]
This does the trick! 🍰

**Review by felddy — APPROVED** [review]
🐕 🔫 😭

**Pull request merged**
